# Generated by Django 3.2.2 on 2021-05-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Health Parameters', max_length=100)),
                ('WBC', models.IntegerField(default=0)),
                ('NEUT', models.FloatField(default=0)),
                ('LYMPH', models.FloatField(default=0)),
                ('RBC', models.FloatField(default=0)),
                ('HCT', models.FloatField(default=0)),
                ('UREA', models.IntegerField(default=0)),
                ('HB', models.IntegerField(default=0)),
                ('CREATININE', models.FloatField(default=0)),
                ('IRON', models.IntegerField(default=0)),
                ('HDL', models.IntegerField(default=0)),
                ('ALKALINE', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Medical Questionnaire', max_length=100)),
                ('isSmoking', models.BooleanField(default=False)),
                ('isOriental', models.BooleanField(default=False)),
                ('isDrugsSensitive', models.BooleanField(default=False)),
                ('hasChronicalDisease', models.BooleanField(default=False)),
                ('isNeedsDiet', models.BooleanField(default=False)),
                ('isEatingToMuchMeat', models.BooleanField(default=False)),
                ('isMalnourished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('autoRec', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(default='Mendy', max_length=100)),
                ('personID', models.CharField(max_length=9, unique=True)),
                ('tel', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('age', models.IntegerField()),
                ('health_param', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.healthparameters')),
                ('questionnaire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.questionnaire')),
                ('visits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient.visit')),
            ],
        ),
    ]
