# Generated by Django 3.2.2 on 2021-05-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20210508_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
    ]
